spring.application.name=hobbyCatalog

server.port=5000

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update

spring.datasource.url=jdbc:postgresql://hobby-db:5432/hobbycatalogdb
spring.datasource.username=postgres
spring.datasource.password=1k2s3e4n

app.jwt.secret = yourVeryStrongSecretKeyForJWTSigningMustBeAtLeast32CharsLong!
#15 min
app.jwt.expirationMs= 900000
#30 min
app.jwt.refreshExpirationMs =1800000