services:
  app:
    container_name: hobby_catalog_container
    ports:
      - "5000:5000"

    environment:
      - DATABASE=jdbc:postgresql://db:5432/hobbycatalogDB
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=1k2s3e4n
    depends_on:
      - db
    networks:
      - hobby-network
  db:
    image: postgres
    container_name: hobby_catalog_container
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/postgresql/data1
    environment:
      POSTGRES_DB: hobbycatalogDB
      POSTGRES_NAME: root
      POSTGRES_PASSWORD: 1k2s3e4n
    ports:
      - "5432:5432"
    networks:
      - app-network


volumes:
  db-data:
networks:
  app-network:
    driver: bridge
